# -*- coding: utf-8 -*-
"""NeuroEducation

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bhivh-x7MVRDd1DUogN2OF2D_eUMYbGt
"""

!nvidia-smi

!pip install ultralytics

from ultralytics import YOLO

!yolo task=detect mode=train model=yolov8l.pt data=../content/drive/MyDrive/Datasets/Trucks/data.yaml epochs=10 imgsz=640